swagger: '2.0'
info:
  title: EMF_Server_Controller
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      operationId: application.hello_world
      summary: "Hello World!"
      tags: [emf_server]
      responses:
        200:
          description: OK
  /app:
    get:
        operationId: application.get_all_apps
        tags: [emf_server]
        summary: "Gets information about all applications"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/ArrayOfApps'
          400:
            description: "Bad request."
          404:
            description: "Not found."
          500:
            description: "Internal server error."
  /app/{appID}:
    get:
        operationId: application.get_app
        tags: [emf_server]
        summary: "Gets information about a specific application"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "appID"
          in: "path"
          description: "ID of the application to get information"
          required: true
          type: "integer"
          format: "int64"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/AppTotalInfo'
          400:
            description: "Bad request."
          404:
            description: "Not found."
          500:
            description: "Internal server error."
    patch:
      operationId: application.change_app_state
      tags: [emf_server]
      summary: "Changes an application state"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "appID"
        in: "path"
        description: "ID of the application to change its state"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "state"
        description: "Application state (true to start, false to stop)"
        required: true
        schema:
          $ref: "#/definitions/AppState"
      responses:
        200:
          description: "OK."
          schema:
              $ref: '#/definitions/AppInfo'
        400:
          description: "Bad request."
        404:
          description: "Not found."
        500:
          description: "Internal server error."
    delete:
        operationId: application.delete_app
        tags: [emf_server]
        summary: "Removes an application from the platform"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "appID"
          in: "path"
          description: "ID of the application to remove"
          required: true
          type: "integer"
          format: "int64"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/AppInfo'
          400:
            description: "Bad request."
          404:
            description: "Not found."
          500:
            description: "Internal server error."
  /app/deploy:
    post:
      operationId: application.deploy_app
      tags: [emf_server]
      summary: "Deploy application in the platform"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "deploy"
        description: "Application object to be deployed"
        required: true
        schema:
          $ref: '#/definitions/AppDeploy'
      responses:
        201:
          description: "Created."
          schema:
              $ref: '#/definitions/AppTotalInfo'
        400:
          description: "Bad request."
        500:
          description: "Internal server error"
  /app/tracing/{appID}:
    get:
        operationId: application.get_app_tracing
        tags: [emf_server]
        summary: "Gets information about tracing of a specific application"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "appID"
          in: "path"
          description: "ID of the application"
          required: true
          type: "integer"
          format: "int64"
        responses:
          200:
            description: "OK."
            schema:
                type: string
                example: 127.0.0.1:8080
          400:
            description: "Bad request."
          404:
            description: "Not found."
          500:
            description: "Internal server error."
            
definitions:
  AppDeploy:
    type: "object"
    required:
    - "name"
    - "docker_image"
    - "stateless"
    - "quality_metrics"
    properties:
      name:
        type: "string"
        example: "Songs Application"
        description: "Name of the application to be deployed"
      docker_image:
        type: "string"
        example: "fcribeiro/Songs_MS"
        description: "Name of the docker image"
      stateless:
          type: "boolean"
          example: true
          description: "For stateless apps use true, stateful use false."
      quality_metrics:
        type: "array"
        items:
          $ref: '#/definitions/QualityMetrics'
  AppTotalInfo:
      type: "object"
      required:
      - "id"
      - "name"
      - "state"
      - "docker_image"
      - "stateless"
      - "quality_metrics"
      properties:
        id:
          type: "integer"
          example: 1
          description: "The application ID."
        name:
          type: "string"
          example: "Songs Application"
          description: "Name of the deployed application"
        state:
          type: "string"
          example: "Running"
          description: "Current state of the application"
        docker_image:
          type: "string"
          example: "fcribeiro/Songs_MS"
          description: "Name of the docker image"
        stateless:
          type: "boolean"
          example: true
          description: "Stateless apps use true, stateful use false."
        quality_metrics:
          type: "array"
          items:
            $ref: '#/definitions/QualityMetrics'
  AppInfo:
      type: "object"
      required:
      - "id"
      - "name"
      - "state"
      properties:
        id:
          type: "integer"
          example: 1
          description: "The application ID."
        name:
          type: "string"
          example: "Songs Application"
          description: "Name of the deployed application"
        state:
          type: "string"
          example: "Stopped"
          description: "Current state of the application"
  ArrayOfApps:
      type: "array"
      items:
        $ref: '#/definitions/AppInfo'
  QualityMetrics:
      type: "object"
      required:
      - "metric"
      - "value"
      properties:
        metric:
          type: "string"
        value:
          type: "string"
  AppState:
      type: "object"
      required:
      - "state"
      properties:
        state:
          type: "boolean"

        
