swagger: '2.0'
info:
  title: EMP_Server_Controller
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      operationId: application.hello_world
      summary: "EMP Working!"
      tags: [emp_server]
      responses:
        200:
          description: OK
          schema:
            type: "string"
  /app:
    get:
        operationId: application.get_all_apps
        tags: [emp_server]
        summary: "Gets general information about all applications"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/ArrayOfApps'
          400:
            description: "Bad request."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"            
          500:
            description: "Internal server error."
            schema:
              type: "string"
    post:
      operationId: application.deploy_app
      tags: [emp_server]
      summary: "Deploys an application in the platform"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "app_info"
        description: "Application object to be deployed"
        required: true
        schema:
          $ref: '#/definitions/AppDeploy'
      responses:
        201:
          description: "Created."
          schema:
              $ref: '#/definitions/AppInfo'
        400:
          description: "Bad request."
          schema:
            type: "string"
        500:
          description: "Internal server error"
          schema:
            type: "string"
  /app/user:
    post:
        operationId: application.create_user
        tags: [emp_server]
        summary: "Creates a user with all the necessary information"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "user_info"
          description: "User information"
          required: true
          schema:
            $ref: '#/definitions/UserInfo'
        responses:
          200:
            description: "User created successfully"
            schema:
              type: "string"
          400:
            description: "Bad request."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"
          500:
            description: "Internal server error."
            schema:
              type: "string"
  /app/login:
    post:
        operationId: application.login_user
        tags: [emp_server]
        summary: "User login"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "user_info"
          description: "User information"
          required: true
          schema:
            $ref: '#/definitions/UserInfo'
        responses:
          200:
            description: "Logged in successfully"
            schema:
              type: "string"
          400:
            description: "Bad request."
            schema:
              type: "string"
          401:
            description: "Login Failed."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"
          500:
            description: "Internal server error."
            schema:
              type: "string"
  /app/{app_id}:
    get:
        operationId: application.get_app
        tags: [emp_server]
        summary: "Gets all information about a specific application"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "app_id"
          in: "path"
          description: "ID of the application to get information"
          required: true
          type: "string"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/AppTotalInfo'
          400:
            description: "Bad request."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"
          500:
            description: "Internal server error."
            schema:
              type: "string"
    patch:
      operationId: application.change_app_state
      tags: [emp_server]
      summary: "Changes an application state"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "app_id"
        in: "path"
        description: "ID of the application to change its state"
        required: true
        type: "string"
      - in: "body"
        name: "app_state"
        description: "Parameters that will change the state of the application"
        required: true
        schema:
          $ref: "#/definitions/AppState"
      responses:
        200:
          description: "OK."
          schema:
              $ref: '#/definitions/AppTotalInfo'
        400:
          description: "Bad request."
          schema:
            type: "string"
        404:
          description: "Not found."
          schema:
            type: "string"
        500:
          description: "Internal server error."
          schema:
            type: "string"
    delete:
        operationId: application.delete_app
        tags: [emp_server]
        summary: "Removes an application from the platform"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "app_id"
          in: "path"
          description: "ID of the application to remove"
          required: true
          type: "string"
        responses:
          200:
            description: "OK."
            schema:
              $ref: '#/definitions/AppInfo'
          400:
            description: "Bad request."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"
          500:
            description: "Internal server error."
            schema:
              type: "string"
  /app/tracing/{app_id}:
    get:
        operationId: application.get_app_tracing
        tags: [emp_server]
        summary: "Gets information about tracing of a specific application"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "app_id"
          in: "path"
          description: "ID of the application"
          required: true
          type: "string"
        responses:
          200:
            description: "OK."
            schema:
                type: "string"
                example: "127.0.0.1:8080"
          400:
            description: "Bad request."
            schema:
              type: "string"
          404:
            description: "Not found."
            schema:
              type: "string"
          500:
            description: "Internal server error."
            schema:
              type: "string"
            
definitions:
  AppDeploy:
    type: "object"
    required:
    - "name"
    - "docker_image"
    - "stateless"
    - "quality_metrics"
    properties:
      name:
        type: "string"
        example: "Songs Application"
        description: "Name of the application to be deployed"
      docker_image:
        type: "string"
        example: "fcribeiro/Songs_MS"
        description: "Name of the docker image"
      stateless:
          type: "boolean"
          example: true
          description: "For stateless apps use true, stateful use false."
      quality_metrics:
        type: "array"
        items:
          $ref: '#/definitions/QualityMetrics'
  AppTotalInfo:
      type: "object"
      properties:
        id:
          type: "string"
          example: "abcABC"
          description: "The application ID."
        name:
          type: "string"
          example: "Songs Application"
          description: "Name of the deployed application"
        state:
          type: "string"
          example: "Running"
          description: "Current state of the application"
        docker_image:
          type: "string"
          example: "fcribeiro/Songs_MS"
          description: "Name of the docker image"
        stateless:
          type: "boolean"
          example: true
          description: "Stateless apps use true, stateful use false."
        quality_metrics:
          type: "array"
          items:
            $ref: '#/definitions/QualityMetrics'
  AppInfo:
      type: "object"
      properties:
        id:
          type: "string"
          example: "abcABC"
          description: "The application ID."
        name:
          type: "string"
          example: "Songs Application"
          description: "Name of the deployed application"
        state:
          type: "string"
          example: "Stopped"
          description: "Current state of the application"
  ArrayOfApps:
      type: "array"
      items:
        $ref: '#/definitions/AppInfo'
  QualityMetrics:
      type: "object"
      required:
      - "metric"
      - "value"
      properties:
        metric:
          type: "string"
        values:
          type: "string"
  AppState:
      type: "object"
      properties:
        state:
          type: "boolean"
        quality_metrics:
          type: "array"
          items: 
            $ref: '#/definitions/QualityMetrics'
  UserInfo:
      type: "object"
      required: 
      - "user_name"
      - "password"
      properties:
        user_name:
          type: "string"
          example: "fcribeiro"
          description: "Username of the user"
        password:
          type: "string"
          example: "ribeiro123"
          description: "Password of the user"
          

        
