# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.environment_variables import EnvironmentVariables  # noqa: F401,E501
from swagger_server.models.quality_metrics import QualityMetrics  # noqa: F401,E501
from swagger_server import util


class AppTotalInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, state: str=None, docker_image: str=None, envs: List[EnvironmentVariables]=None, stateless: bool=None, quality_metrics: List[QualityMetrics]=None, port: int=None, replicas: int=None, external_ip: str=None):  # noqa: E501
        """AppTotalInfo - a model defined in Swagger

        :param id: The id of this AppTotalInfo.  # noqa: E501
        :type id: str
        :param name: The name of this AppTotalInfo.  # noqa: E501
        :type name: str
        :param state: The state of this AppTotalInfo.  # noqa: E501
        :type state: str
        :param docker_image: The docker_image of this AppTotalInfo.  # noqa: E501
        :type docker_image: str
        :param envs: The envs of this AppTotalInfo.  # noqa: E501
        :type envs: List[EnvironmentVariables]
        :param stateless: The stateless of this AppTotalInfo.  # noqa: E501
        :type stateless: bool
        :param quality_metrics: The quality_metrics of this AppTotalInfo.  # noqa: E501
        :type quality_metrics: List[QualityMetrics]
        :param port: The port of this AppTotalInfo.  # noqa: E501
        :type port: int
        :param replicas: The replicas of this AppTotalInfo.  # noqa: E501
        :type replicas: int
        :param external_ip: The external_ip of this AppTotalInfo.  # noqa: E501
        :type external_ip: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'state': str,
            'docker_image': str,
            'envs': List[EnvironmentVariables],
            'stateless': bool,
            'quality_metrics': List[QualityMetrics],
            'port': int,
            'replicas': int,
            'external_ip': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'state': 'state',
            'docker_image': 'docker_image',
            'envs': 'envs',
            'stateless': 'stateless',
            'quality_metrics': 'quality_metrics',
            'port': 'port',
            'replicas': 'replicas',
            'external_ip': 'external_ip'
        }

        self._id = id
        self._name = name
        self._state = state
        self._docker_image = docker_image
        self._envs = envs
        self._stateless = stateless
        self._quality_metrics = quality_metrics
        self._port = port
        self._replicas = replicas
        self._external_ip = external_ip

    @classmethod
    def from_dict(cls, dikt) -> 'AppTotalInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppTotalInfo of this AppTotalInfo.  # noqa: E501
        :rtype: AppTotalInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AppTotalInfo.

        The application ID.  # noqa: E501

        :return: The id of this AppTotalInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AppTotalInfo.

        The application ID.  # noqa: E501

        :param id: The id of this AppTotalInfo.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this AppTotalInfo.

        Name of the deployed application  # noqa: E501

        :return: The name of this AppTotalInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AppTotalInfo.

        Name of the deployed application  # noqa: E501

        :param name: The name of this AppTotalInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def state(self) -> str:
        """Gets the state of this AppTotalInfo.

        Current state of the application  # noqa: E501

        :return: The state of this AppTotalInfo.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this AppTotalInfo.

        Current state of the application  # noqa: E501

        :param state: The state of this AppTotalInfo.
        :type state: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def docker_image(self) -> str:
        """Gets the docker_image of this AppTotalInfo.

        Name of the docker image  # noqa: E501

        :return: The docker_image of this AppTotalInfo.
        :rtype: str
        """
        return self._docker_image

    @docker_image.setter
    def docker_image(self, docker_image: str):
        """Sets the docker_image of this AppTotalInfo.

        Name of the docker image  # noqa: E501

        :param docker_image: The docker_image of this AppTotalInfo.
        :type docker_image: str
        """
        if docker_image is None:
            raise ValueError("Invalid value for `docker_image`, must not be `None`")  # noqa: E501

        self._docker_image = docker_image

    @property
    def envs(self) -> List[EnvironmentVariables]:
        """Gets the envs of this AppTotalInfo.


        :return: The envs of this AppTotalInfo.
        :rtype: List[EnvironmentVariables]
        """
        return self._envs

    @envs.setter
    def envs(self, envs: List[EnvironmentVariables]):
        """Sets the envs of this AppTotalInfo.


        :param envs: The envs of this AppTotalInfo.
        :type envs: List[EnvironmentVariables]
        """
        if envs is None:
            raise ValueError("Invalid value for `envs`, must not be `None`")  # noqa: E501

        self._envs = envs

    @property
    def stateless(self) -> bool:
        """Gets the stateless of this AppTotalInfo.

        Stateless apps use true, stateful use false.  # noqa: E501

        :return: The stateless of this AppTotalInfo.
        :rtype: bool
        """
        return self._stateless

    @stateless.setter
    def stateless(self, stateless: bool):
        """Sets the stateless of this AppTotalInfo.

        Stateless apps use true, stateful use false.  # noqa: E501

        :param stateless: The stateless of this AppTotalInfo.
        :type stateless: bool
        """
        if stateless is None:
            raise ValueError("Invalid value for `stateless`, must not be `None`")  # noqa: E501

        self._stateless = stateless

    @property
    def quality_metrics(self) -> List[QualityMetrics]:
        """Gets the quality_metrics of this AppTotalInfo.


        :return: The quality_metrics of this AppTotalInfo.
        :rtype: List[QualityMetrics]
        """
        return self._quality_metrics

    @quality_metrics.setter
    def quality_metrics(self, quality_metrics: List[QualityMetrics]):
        """Sets the quality_metrics of this AppTotalInfo.


        :param quality_metrics: The quality_metrics of this AppTotalInfo.
        :type quality_metrics: List[QualityMetrics]
        """
        if quality_metrics is None:
            raise ValueError("Invalid value for `quality_metrics`, must not be `None`")  # noqa: E501

        self._quality_metrics = quality_metrics

    @property
    def port(self) -> int:
        """Gets the port of this AppTotalInfo.

        Port number of the application  # noqa: E501

        :return: The port of this AppTotalInfo.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port: int):
        """Sets the port of this AppTotalInfo.

        Port number of the application  # noqa: E501

        :param port: The port of this AppTotalInfo.
        :type port: int
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def replicas(self) -> int:
        """Gets the replicas of this AppTotalInfo.

        Number of replicas of an application  # noqa: E501

        :return: The replicas of this AppTotalInfo.
        :rtype: int
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas: int):
        """Sets the replicas of this AppTotalInfo.

        Number of replicas of an application  # noqa: E501

        :param replicas: The replicas of this AppTotalInfo.
        :type replicas: int
        """
        if replicas is None:
            raise ValueError("Invalid value for `replicas`, must not be `None`")  # noqa: E501

        self._replicas = replicas

    @property
    def external_ip(self) -> str:
        """Gets the external_ip of this AppTotalInfo.

        External IP of the application  # noqa: E501

        :return: The external_ip of this AppTotalInfo.
        :rtype: str
        """
        return self._external_ip

    @external_ip.setter
    def external_ip(self, external_ip: str):
        """Sets the external_ip of this AppTotalInfo.

        External IP of the application  # noqa: E501

        :param external_ip: The external_ip of this AppTotalInfo.
        :type external_ip: str
        """
        if external_ip is None:
            raise ValueError("Invalid value for `external_ip`, must not be `None`")  # noqa: E501

        self._external_ip = external_ip
