# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.quality_metrics import QualityMetrics  # noqa: F401,E501
from swagger_server import util


class AppState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: bool=None, quality_metrics: List[QualityMetrics]=None):  # noqa: E501
        """AppState - a model defined in Swagger

        :param state: The state of this AppState.  # noqa: E501
        :type state: bool
        :param quality_metrics: The quality_metrics of this AppState.  # noqa: E501
        :type quality_metrics: List[QualityMetrics]
        """
        self.swagger_types = {
            'state': bool,
            'quality_metrics': List[QualityMetrics]
        }

        self.attribute_map = {
            'state': 'state',
            'quality_metrics': 'quality_metrics'
        }

        self._state = state
        self._quality_metrics = quality_metrics

    @classmethod
    def from_dict(cls, dikt) -> 'AppState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppState of this AppState.  # noqa: E501
        :rtype: AppState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> bool:
        """Gets the state of this AppState.


        :return: The state of this AppState.
        :rtype: bool
        """
        return self._state

    @state.setter
    def state(self, state: bool):
        """Sets the state of this AppState.


        :param state: The state of this AppState.
        :type state: bool
        """

        self._state = state

    @property
    def quality_metrics(self) -> List[QualityMetrics]:
        """Gets the quality_metrics of this AppState.


        :return: The quality_metrics of this AppState.
        :rtype: List[QualityMetrics]
        """
        return self._quality_metrics

    @quality_metrics.setter
    def quality_metrics(self, quality_metrics: List[QualityMetrics]):
        """Sets the quality_metrics of this AppState.


        :param quality_metrics: The quality_metrics of this AppState.
        :type quality_metrics: List[QualityMetrics]
        """

        self._quality_metrics = quality_metrics
