# coding: utf-8

"""
    EMP_Server_Controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.app_total_info import AppTotalInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestAppTotalInfo(unittest.TestCase):
    """AppTotalInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppTotalInfo(self):
        """Test AppTotalInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.app_total_info.AppTotalInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
