# coding: utf-8

"""
    EMP_Server_Controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.app_state import AppState  # noqa: E501
from swagger_client.rest import ApiException


class TestAppState(unittest.TestCase):
    """AppState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppState(self):
        """Test AppState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.app_state.AppState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
