# Service for songs-deployment
kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
  - port: 5003
    targetPort: 5003
---
# Deployment for Authentication_MS

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: fcribeiro/authentication_ms_p3
        env:
        - name: USERSADDRESS
          value: "127.0.0.1"
        ports:
        - containerPort: 5003