---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:1.20
        env:
        - name: SCRIBE_ENABLED
          value: "false"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: 10.11.243.189:9092 
        ports:
        - name: http
          containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - name: http
    port: 80
    targetPort: 9411