---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    app: zipkin
  template:
    metadata:
      name: zipkin
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: fcribeiro/zipkin-emp
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.11.243.15:9092"
        - name: KAFKA_TOPIC
          value: "zipkin"
        ports:
        - name: http
          containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
  - name: http
    port: 80
    targetPort: 9411