# coding: utf-8

"""
    EMP_Server_Controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.quality_metrics import QualityMetrics  # noqa: F401,E501


class AppState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'bool',
        'quality_metrics': 'list[QualityMetrics]'
    }

    attribute_map = {
        'state': 'state',
        'quality_metrics': 'quality_metrics'
    }

    def __init__(self, state=None, quality_metrics=None):  # noqa: E501
        """AppState - a model defined in Swagger"""  # noqa: E501

        self._state = None
        self._quality_metrics = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if quality_metrics is not None:
            self.quality_metrics = quality_metrics

    @property
    def state(self):
        """Gets the state of this AppState.  # noqa: E501


        :return: The state of this AppState.  # noqa: E501
        :rtype: bool
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AppState.


        :param state: The state of this AppState.  # noqa: E501
        :type: bool
        """

        self._state = state

    @property
    def quality_metrics(self):
        """Gets the quality_metrics of this AppState.  # noqa: E501


        :return: The quality_metrics of this AppState.  # noqa: E501
        :rtype: list[QualityMetrics]
        """
        return self._quality_metrics

    @quality_metrics.setter
    def quality_metrics(self, quality_metrics):
        """Sets the quality_metrics of this AppState.


        :param quality_metrics: The quality_metrics of this AppState.  # noqa: E501
        :type: list[QualityMetrics]
        """

        self._quality_metrics = quality_metrics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppState):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
